### ISSUE TITLE
Array slice on object, scalar response or not?

### ISSUE THREAD

**Issue by cburgmer** [codeniko/JsonPathKt#5]
Running the array slice operator (e.g. `$[1:3]`) against an object (e.g. `{}`) currently returns `null` (see https://cburgmer.github.io/json-path-comparison/results/array_slice_on_object.html#Kotlin_com.nfeld.jsonpathlite).

As a user I would probably expect `[]` instead, considering the query is supposed to return multiple matches?

**Comment by hf-kklein** [comment]
> see https://cburgmer.github.io/json-path-comparison/results/array_slice_on_object.html#Kotlin_com.nfeld.jsonpathlite).

But this repository is about "Java (com.jayway.jsonpath) ¹ ³" not about Kotlin jsonpathlite.

**Comment by cburgmer** [comment]
I'm not sure I understand your answer.

The link mentions all implementations, but the anchor highlights the Kotlin example, which is why I'm raising the issue here.

**Comment by hf-kklein** [comment]
sorry @cburgmer . I was wrong. My fault.

**Comment by codeniko** [comment]
Hi again, yes you're right, makes sense to return `[]` in this case

**Comment by codeniko** [comment]
This is addressed now for the upcoming version 2.0.0 release. I did a similar change for selectors like `$[1,2,3]` on a JSON object

**Comment by codeniko** [comment]
2.0.0 is now released addressing this issue, closing
