### ISSUE TITLE
Support for netty and webflux?

### ISSUE THREAD

**Issue by AtticusLv** [codeniko/JsonPathKt#8]
Hi, is this tool(optimized from JsonPath) supports webflux and netty project?

**Comment by codeniko** [comment]
I haven't tested webflux or netty specifically. It's Kotlin which also runs on JVM. It should be able to run anywhere where JsonPath is able to run.

**Comment by AtticusLv** [comment]
thanks for the answer. 
btw, using JsonPath
if i have a json like below structure
```
[
{
"a": 1
},{
"a": 2
}
]
```
how can i read node "a" value, and re-construct a new json like below structure?
```
{
"saa":[1, 2]
}
```

**Comment by codeniko** [comment]
You can get the values `[1, 2]` with either of the following two json paths, whichever is more convenient to you:
```kotlin
JsonPath.parse("""[{"a": 1},{"a": 2}]""")!!.read<List<Int>>("$[*].a")
JsonPath.parse("""[{"a": 1},{"a": 2}]""")!!.read<JsonNode>("$[*].a")
```

Json paths in general wont create any custom object keys for you. It only retrieves values at your requested path. In this case, it will get you `[1, 2]`. Now having those values, it's up to you to consume them and put them in your expected output object.
