### ISSUE TITLE
Got null value when trying to get nested value inside array

### ISSUE THREAD

**Issue by niciosity** [codeniko/JsonPathKt#9]
Hello, given this JSON...

```
{
    "key": {
        "value": "root key value"
    },
    "array": [
        {
            "name": "name 0",
            "content": "content 0",
            "key": {
                "value": "key value 0"
            }
        },
        {
            "name": "name 1",
            "content": "content 1",
            "key": {
                "value": "key value 1"
            }
        }
    ]
}
```

And I read the "array[1]" with these codes

```
val value = JsonPath.parse(json)?.read<String>("$.array[1].key.value")
```

Got `key value 1` as expected.

```
val values = JsonPath.parse(json)?.read<List<String>>("$.array[1].['name','content','key.value']")
```

Got `[name 1, content 1]` only not the 3rd one. Expected `[name 1, content 1, key value 1]` as a result from this code.

Please investigate. Thank you very much.

**Comment by codeniko** [comment]
Hi, your json path is using `attachments` as key instead of the `array` key in the json you provided. `attachments` doesnt exist so you get null.

For your second problem, that 3rd 'key.value' key does not exist so it's excluded. I understand you're probably expecting it to actually evaluate the inner expression but json object keys can technically have dots and so that's a valid key string.

**Comment by niciosity** [comment]
Sorry I copied the wrong code. I just tried it again and scope the issue to...

`val value1 = jsonNode.read<String>("$.array[1].['key.value']")`

Got `null`, expected `key value 1`.

`val value1 = jsonNode.read<List<String>>("$.array[1].['name','content','key.value']")`

Got `[name 1, content 1]` only not the 3rd one. Expected `[name 1, content 1, key value 1]` as a result from this code.


The `val value1 = jsonNode.read<String>("$.array[1].key.value")` , got `key value 1` as expected.

**Comment by niciosity** [comment]
Ok, I misunderstand the field name inside quote. The `'key.value'` can't be treated as `key.value`. Thanks for your time.
